baseURL: 
languageCode: en-us
theme: raditian-free-hugo-theme-data-science
params:
  footer:
    copyright: © Izzy Bedichek. All rights reserved.
    site_logo:
      _2x: img/showcase/dev_field.png
      alt: developing field joke
      x: img/showcase/dev_field.png
  googleAnalyticsID: ''
  logo:
    text1: Izzy
    text2: Bedichek
  plugins:
    css:
      - URL: css/main.css
      - URL: css/rad-icons.css
      - URL: css/custom.css
    js:
      - URL: js/rad-animations.js
      - URL: js/sticky-header.js
      - URL: js/library/fontfaceobserver.js
  sections:
    - showcase
    - about
    - client_and_work
    - experience
    - education
    - testimonial
    - contact
    - newsletter
menu:
  footer:
    - URL: '#about'
      name: About
      weight: 2
    - URL: '#portfolio'
      name: Portfolio
      weight: 3
    - URL: '#contact'
      name: Contact
      weight: 4
  header:
    - URL: '#about'
      name: About
      weight: 2
    - URL: '#portfolio'
      name: Portfolio
      weight: 3
    - URL: '#contact'
      name: Contact
      weight: 4
